name: Deploy to Vultr

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Desplegando en Vultr via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ ! -d "/root/SignBridge" ]; then
              git clone git@github.com:miguel110301/SignBridge.git /root/SignBridge
            fi
            cd /root/SignBridge
            git pull origin main
            
            # 1. Construir el Frontend
            cd client
            npm install
            npm run build
            
            # 2. Configurar el Server
            cd ../server
            npm install
            
            # 3. Reiniciar la App
            pm2 restart signbridge-api || pm2 start index.js --name signbridge-api